// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChg3eY0zm-BJ5CIXDfaWwzMw_iraS2vQY',
    appId: '1:1053081788408:web:ee2e6db0f4b21f4fa5c00d',
    messagingSenderId: '1053081788408',
    projectId: 'ocari-ed7da',
    authDomain: 'ocari-ed7da.firebaseapp.com',
    storageBucket: 'ocari-ed7da.firebasestorage.app',
    measurementId: 'G-4QS72D5YXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC-gzCVbkaWsz146fc14dC1WqsD7Bs-IE',
    appId: '1:1053081788408:android:bb2cf7c640e8d33da5c00d',
    messagingSenderId: '1053081788408',
    projectId: 'ocari-ed7da',
    storageBucket: 'ocari-ed7da.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABJggfsX-4HWk2HRShdswW1zuVeKSQkXs',
    appId: '1:1053081788408:ios:724f2c237f80458ea5c00d',
    messagingSenderId: '1053081788408',
    projectId: 'ocari-ed7da',
    storageBucket: 'ocari-ed7da.firebasestorage.app',
    iosBundleId: 'com.abatista.ocari',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABJggfsX-4HWk2HRShdswW1zuVeKSQkXs',
    appId: '1:1053081788408:ios:724f2c237f80458ea5c00d',
    messagingSenderId: '1053081788408',
    projectId: 'ocari-ed7da',
    storageBucket: 'ocari-ed7da.firebasestorage.app',
    iosBundleId: 'com.abatista.ocari',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChg3eY0zm-BJ5CIXDfaWwzMw_iraS2vQY',
    appId: '1:1053081788408:web:ba434680e6016d81a5c00d',
    messagingSenderId: '1053081788408',
    projectId: 'ocari-ed7da',
    authDomain: 'ocari-ed7da.firebaseapp.com',
    storageBucket: 'ocari-ed7da.firebasestorage.app',
    measurementId: 'G-1ZDVX77XW9',
  );
}
